version: '3'
services:
    ansible:
          container_name: ansible
          image: ansible
          tty: true
          stdin_open: true
          build: 
                  context: ./
          networks:
                    - net
    remote_host_one:
          container_name: remote_host_one
          image: remote_host_ssh
          build:
                  context: ./ssh-enabled-ubuntu
          networks:
                    - net
    remote_host_two:
          container_name: remote_host_two
          image: remote_host_ssh
          build:
                  context: ./ssh-enabled-ubuntu
          networks:
                  - net


networks:
        net:
          