---
# tasks file for grafana
- name: Install a .deb package
  become: yes  
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_7.3.4_amd64.deb
    
- name: Start grafana-server Service
  become: yes
  systemd:
    state: started
    name: grafana-server
    enabled: yes

- name: Check if grafana was accessible
  uri:
    url: http://localhost:3000
    method: GET
    status_code: 200